config/routes.rb
Rails.application.routes.draw do
  
  resources :violations

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/violation.rb
class Violation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
end

app/controllers/violations_controller.rb
class ViolationsController < ApplicationController

  def index

    # @violations = Violation.find_by(:keyword)

    plaster_count = Violation.where("keyword = ?", "Plaster/Paint").count
    mold_count = Violation.where("keyword = ?", "Mold").count
    fire_hazard_count = Violation.where("keyword = ?", "Fire Hazard").count
    water_leak_count = Violation.where("keyword = ?", "Water Leak").count
    bathroom_count = Violation.where("keyword = ?", "Bathroom").count
    infestation_count = Violation.where("keyword = ?", "Insect/rodent infestation").count
    co_count = Violation.where("keyword = ?", "CO Detector").count
    window_count = Violation.where("keyword = ?", "Window").count
    lock_count = Violation.where("keyword = ?", "Broken Lock").count
    water_count = Violation.where("keyword = ?", "Water/Plumbing").count
    el_count = Violation.where("keyword = ?", "Electrical").count

    gon.data = [
    {keyword: "Plaster/Paint",    value:  plaster_count},
    {keyword: "Mold",    value:  mold_count},
    {keyword: "Fire Hazard",     value: fire_hazard_count},
    {keyword: "Water Leak",   value: water_leak_count},
    {keyword: "Bathroom",   value: bathroom_count},
    {keyword: "Infestation",   value: infestation_count},
    {keyword: "CO Detector",   value: co_count},
    {keyword: "Window",   value: window_count},
    {keyword: "Broken Lock",   value: lock_count},
    {keyword: "Water/Plumbing",   value: water_count},
    {keyword: "Electrical",   value: el_count},
    ]

    
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HousingViolations</title>
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://d3js.org/d3.v5.min.js" ></script>
  
  </head>
  <body>

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">HousingViolations</a>
    </div>

    <div class="collapse navbar-collapse" id="primary_nav_wrap">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Issue<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Plater/Paint</a></li>
            <li><a href="#">Infestation</a></li>
            <li><a href="#">Water Leak</a></li>
            <li><a href="#">Fire Hazard</a></li>
            <li><a href="#">Mold</a></li>
            <li><a href="#">Broken Window</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Boro<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Manhattan</a></li>
            <li><a href="#">Brooklyn</a></li>
            <li><a href="#">Bronx</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

    
    <%= yield %>
  
  
  </body>
</html>

app/views/violations/index.html.erb
<%# <%= render partial: "bar_chart", locals: {data: @data} %>
<svg class="chart"></svg>

app/views/welcome/index.html.erb
<div class="landing-page">
  <p class="well well-lg col-md-8 col-md-offset-2 text-center">New York City Housing Authority's units are at most 50 years old and have a huge backlog of repairs.
   This is due mostly to budget cuts from Congress and Albany. The authority faces roughly $16 billion in unmet capital needs. <br> Yet many people continue to live in apartments that are not just deteriorating but are often ovecrowded too. <br><br>Learn more about these repair issues:</p>

</div><br>
<div class= "col-md-8 col-md-offset-2 text-center">
<a href="<%=violations_path%>"><button class="btn btn-default">view charts</button></a>
</div> 